# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ba7bd72e51b5014c4cac7171546172181abda613f9c9a4f8bfaab386e53a0064d7d4ae2a972fd6a5574e93ad2097ef86b3ad9de3c4296c3b367043050bb85e

test:
  secret_key_base: 0334e48650ed71cd458a692e2f6c4303b091a968f5c50fdb0724a3021197ca836088f117cf28586a80c6268731b09e0921f4960967d6aa59720e5ca32e32d9de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
